### ISSUE TITLE
Habits and living conditions are collected but not displayed

### ISSUE THREAD

**Issue by mateuszkrasucki** [iryonetwork/wwm#109]
- Questionnaire with questions about habits and living conditions is present in medical history form but information collected there are displayed nowhere.
- Does habits and living conditons belong to "medical history"???

**Comment by PeterKuralt** [comment]
Habits and living conditions belong to the Medical History and should be visible and accessible under the Medical History. According to the access control Medical History is visible for all users in a slightly adjusted view.

**Comment by mateuszkrasucki** [comment]
Fixed as part of issue #165
