### ISSUE TITLE
Doctor's view consolidation

### ISSUE THREAD

**Issue by PeterKuralt** [iryonetwork/wwm#137]
Inside the doctor's view we have the following list of categories under menu _Menu_:

a) In Consultation
b) Medical History
c) Personal Info
d) Health record

The correct number and order of the categories should be:

a) In Consultation
b) Medical Data
c) Medical History
d) Medical Record
e) Personal Info

Under Menu there should be menu _Actions_ with the following categories:

a) Add Diagnosis
b) Add  Medical Data

**Comment by mateuszkrasucki** [comment]
1. What is desired state of Medical Data tab? Are we aiming at achieving the graph of collected data as in prototype in this milestone? 
2. Medical data are currently stored as part of encounter and as such available in Health (Medical) record)

**Comment by PeterKuralt** [comment]
1. The desired state of the Medical Data is to show charts of gathered data. We will add this feature in the next version. I would, if possible, still expose data in form of cards with value and timestamp under this category already in the MVP. Same as we have at the moment under the category Medical Record.

2. Medical data need to be exposed under Medical Record as well, since there is association between medical data and certain complaint.

**Comment by mateuszkrasucki** [comment]
@1. So do we want to expose there latest readings for each category?

**Comment by PeterKuralt** [comment]
@1. It is supposed to be total histogram of values, exposing the deltas associated with different health events. For MVP let us do as you propose, so exposing latest reading for each category.

Please bear in mind that we have 2 separate sub-categories:

a) Body Measurments (Height, Weight and BMI)
b) Vital Signs (Temperature, Blood Pressure etc.)

**Comment by mateuszkrasucki** [comment]
Resolved.
