### ISSUE TITLE
Define expected value range for basic clinical data

### ISSUE THREAD

**Issue by PeterKuralt** [iryonetwork/wwm#210]
In order to avoid user input mistakes, we need to define expected ranges for the following clinical data.

1.) Weight
2.) Height
3.) Blood pressure
4.) Temperature
5.) Heart Rate
6.) Sp02

Propositions:

1.) Recorded weight for humans can range from 1kg to 650 kgs. Since we won't be associating weight with age I suggested to set warning for the values under 20kg and for the values above 180 kgs. Considering weight at birth the smallest ever recorded is 227g while the highest ever recorded is 10432g which is why I suggest to set a warning for values under 350g and values above 6500g.

2.) Recorded height for humans can range from 22 cm (smallest premature baby born) to 272 cm (tallest man ever lived). Inside this range I would set a warning for values above 220cm and below 100cm for elders and children. Considering height at birth I would suggest to set a warning for values below 35 cm and values above 65 cm.

3.) Measurable blood pressure range is defined by device. Most devices record values from 0 to 299 mmHg. I propose to set warning at:

- systolic: if above 170 or under 60
- disatolic: if above 105 or under 45  

4.) Body temperature ranges between 24 -26 to 46 degrees Celsius (Highest ever recorded). I propose to set warning at 31 degrees Celsius (most people with body temperature under 31 degrees would be unconscious or comatose) and 43 degrees Celsius (most people would be dead or would have serious brain damage)

5.) There is no records of highest heart rate recorded. A general formula for highest heart rate is 220 minus age. I.e. 220 - 30 = 190. However heart rates above 220 may occur but mostly while performing sports activities. Also people with heart rate under 35 exist (mostly sportsmen). I suggest to allow range between 0 - 300 and set warning for values above 180 and values under 40.  
    
6.) When using pulse oximeter which measures pressure of oxygen in blood, SpO2 values can range from 0 - 100%. Values from 95-100% are considered as normal, while values under 90% are considered as symptomatic.  Levels under 65% percent shows serious oxygen deficit and potential state of unconsciousness. I propose to set a warning for levels under 70%.

**Comment by mateuszkrasucki** [comment]
Expected range validators were defined & implemented.
