### ISSUE TITLE
Implement organisation, location, clinic storage

### ISSUE THREAD

**Issue by mateuszkrasucki** [iryonetwork/wwm#24]
1. There needs to be registry of organisations, locations and clinics together with specified metadata (https://docs.google.com/spreadsheets/d/1StuS-0MMf97skfrQxehZl3CA_4d8UQrCNZtdB18ZX6o/edit#gid=0). User belongs to location, location belong to the partner.
2. New data is to be stored together with auth data and synced together with it. 

FOLLOW-UP: User can authenticate to location/clinic s/he belongs to.

**Comment by dominikznidar** [comment]
I think number 2 should be handled separately after this is completed.

**Comment by mateuszkrasucki** [comment]
@dominikznidar Ok

**Comment by mateuszkrasucki** [comment]
- [ ] Add default auth users to default dev locations from https://github.com/iryonetwork/wwm/pull/29
- [ ] Ensure that users can login "to" and access data from location (rule)

**Comment by mateuszkrasucki** [comment]
## Proposal for changes in Auth to facilitate clinic, location, organisation & correct access control

### Starting point
#### Entities
Originally Auth had following entities (the ones in italic are transient, not in storage)
- **User**
   - id, username, password

- **Role**
   - id, name
   - users: array of **UserIDs**

- **Rule**
  - id, subject, resource, action [read / write / delete], deny [true/false]

- *ValidationPair*
  - resource, actions [read / write / delete]

- *ValidationResult*
  - query (original ValidationPair)
  - result [ bool] 

#### Behaviour
User is added to role, not role to user. Casbin configuration is following:
```
[request_definition]
r = sub, obj, act
[policy_definition]
p = sub, obj, act, eft
[role_definition]
g = _, _
[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))
[matchers]
m = g(r.sub, p.sub) && (wildcardMatch(r.obj, p.obj) || selfMatch(r.obj, p.obj, r.sub)) && binaryMatch(r.act, p.act)
```

### How I've implemented organisation, clinic, location originally [as in PR]
#### Entities
Entities in *italic* are transient, not in storage.

- **User**
   - id, username, password
   - personalData [object containing all the metadata defined by Peter: firstName, middleName, lastName, dateOfBirth, specialisation, nationality, residency, passport data [object: number, issuingCountry, expiryDate], licenses [array of strings], languages [array of strings]
   - roles: array of *roleIDs*
   - clinics: array of *clinicIDs*
   - organisations: array of *organizationIDs*

- **Role**
   - id, name
   - users : array of *userIDs*

- **Organization**
  - id, name, address [object: addressLine1, addressLine2, postCode, city, country], legalStatus, serviceType, representative [object ContactData: name, email, phoneNumber], primaryContact [object ContactData]
  - users: array of *userIDs*
  - clinics: array of *clinicIDs*

- **Location**
  - id, name, country, city, manager [object ContactData], capacity [integer], waterSupply [bool], electricity [bool]
  - clinics: array of *clinicIDs*

- **Clinic**
  - id, name
  - location: *locationID*
  - organization: *organizationID*
  - users: array of *userIDs*

- **Rule**
  - id, subject, resource, action [read / write / delete], deny [true/false]

- *ValidationPair*
  - resource, actions [read / write / delete]

- *ValidationResult*
  - query (original ValidationPair)
  - result [ bool] 

#### Behaviour
1. User can be added to role, role can be added to user; both are updated (within one bolt transaction). 
2. User can be added to organisation, organisation can be added to user; both are updated (within one bolt transaction). 
3. Clinic is essentially created by defining organisation + location relationship. 
4. User can be added to clinic, clinic can be added to user; both are updated (within one bolt transaction). 
5. Users belong to locations based on belonging to clinic. 
5. First Casbin configuration and loaded policy line remained completely unchanged that meant that users still maintained *roles* across whole system. Later I've added **location** as casbin *domain* and when loading roles to Casbin specified that user hold a given role for every location s/he belongs to. It worked nicely (right now PR is broken with failing tests but that's due to some additional experiments) but it's not really what we need/want I believe :) 

### How I want to change things
1. First, since we introduce **domain** into casbin model we should make it actually first-class citizen of the whole auth model. As I see, to allow flexibility the domain of the role could be basically anything or in our case:
  - user itself (I have rights to "myself")
  - clinic
  - organisation 
  - location
  - "wildcard" - applies to everything

2. Instead of simply assigning users to clinic organisations and clinics we should use "roles" as what defines those relationships. 

Examples:
```
New user is added at the same time assigned to organisation XYZ; user has following roles in the system: 
   - everyoneRole on domain "__user__{self_ID}" 
   - everyoneRole on domain "__organization__{XYZ_ID}"
Later the user is added as a doctor to clinic ZYX run by organization XYZ in location YXZ and how we store this relationship is assigning to the user new roles:
   - doctorRole on domain "__clinic__{ZYX_ID}"
   - doctorRole on domain "__location__{YXZ_ID}"
```
```
Melissa should be able to access & modify everything. She will have following roles:
   - everyoneRole on domain "__user__{self_ID}"" 
   - superAdminRole on domain "__*__*" 
```
```
Doctor working for WWM directly should be able to access & modify all clinical data as he's managing this for Melissa. S/he will have following roles:
   - everyoneRole on domain "__user__{self_ID}"" 
   - doctorRole on domain "__clinic__*"
   - doctorRole on domain "__location__*"
```

**As in example: holding a given role at the clinic, automatically adds the role for the location of the clinic.**


3. Additional action should be added alongside [read / write / delete]: *update*. 

#### Entities
Following entities are in storage (the ones in italic are transient, not in storage)
- **User**
   - id, username, password
   - personalData [object containing all the metadata defined by Peter: firstName, middleName, lastName, dateOfBirth, specialisation, nationality, residency, passport data [object: number, issuingCountry, expiryDate], licenses [array of strings], languages [array of strings]
   - roles, *object with following structure*:
     - domainType
       - domainID
         - array of roleIDs

- **Role**
   - id, name

   *We will loose list of all the users holding a role but it seems meaningless as it is per domain always anyway.*

- **Organization**
  - id, name, address [object: addressLine1, addressLine2, postCode, city, country], legalStatus, serviceType, representative [object ContactData: name, email, phoneNumber], primaryContact [object ContactData]
  - clinics: array of **clinicIDs**
  - users, *object with following structure*:
    - userID
      - array of roleIDs

- **Location**
  - id, name, country, city, manager [object ContactData], capacity [integer], waterSupply [bool], electricity [bool]
  - clinics: array of **clinicIDs**

- **Clinic**
  - id, name
  - location: **locationID**
  - organization: **organizationID**
  - users, *object with following structure*:
    - userID
      - array of roleIDs

- **Rule**
  - id, subject, resource, action [read / write / delete / update], deny [true/false]
  - domain
- *ValidationPair*
  - resource, actions [read / write / delete / update]
  - domain
- *ValidationResult*
  - query (original ValidationPair)
  - result [ bool] 

#### Behaviour
1. Role can be added to user on domain; both user and domain entities are updated (within one bolt transaction). Some roles are default (everyoneRole on self-domain), some roles can be added for wildcard domains. 
3. Clinic is essentially created by defining organisation + location relationship. 
3. Users belong to locations based on belonging to clinic. 
4. Casbin configuration looks fillowing [not tested yet but something like that will work I believe[:
```
[request_definition]
r = sub, dom, obj, act
[policy_definition]
p = sub, dom, obj, act, eft
[role_definition]
g = _, _, _
[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))
[matchers]
m = (g(r.sub, p.sub, r.dom) ||  g(r.sub, p.sub, "__user__*") ||  g(r.sub, p.sub, "__organization__*")  ||  g(r.sub, p.sub, "__clinic__*") ||  g(r.sub, p.sub, "__location__*") ||  g(r.sub, p.sub, "__*__*")) && (wildcardMatch(r.obj, r.dom, p.obj, p.dom) || selfMatch(r.obj, p.obj, r.sub)) && binaryMatch(r.act, p.act)`)
```
5. All API calls within system itself will be validated with *clinic* domain. Some additional validations checks inside might have *location* domain. Dashboard calls will have __*__* domain for highest level *organisation* domain for managing organization, *user domain* for editing own data etc.

**Comment by mateuszkrasucki** [comment]
done and merged.
