### ISSUE TITLE
Add cloud services availability service and service status (health) package

### ISSUE THREAD

**Issue by mateuszkrasucki** [iryonetwork/wwm#6]
1. Add a service that will ping cloud services (storage, auth) to determine their availability and one external (independent) resource to determine internet status. 
    - Service should expose and endpoint for the frontend to fetch the status. 
```
{"status": {"storage": "OK", "auth": "OK", "internet": "OK"}}
```
    - Service should have a logic to mark resources as unavailable only after X attempts. 
    - Service should also collect status of local services to ease troubleshooting. 

2. Status package should be added to easily expose status of internal services (and build later on top of simple ping logic).

**Comment by dominikznidar** [comment]
Is already implemented in the `status` service
