### ISSUE TITLE
Remove all references to "tent" & "camp"

### ISSUE THREAD

**Issue by mateuszkrasucki** [iryonetwork/wwm#97]
- As in majority of cases refugees in Jordan don't live in refugee camps all references to tents and camps should be removed. 
- Patient personal data were already updated top include "region" & "address" instead of "camp" & tent
- Following questions from **medical history** need to be changed:
    - Does your tent have heating?
    - Does your tent have electricity?

**Comment by PeterKuralt** [comment]
This is specific for the Jordan, since in Lebanon refugees live in camps. Reference to camp and tent was requested by Melissa. I would leave these two but they should not be mandatory fields. So user can register data or not according to the needs.

**Comment by PeterKuralt** [comment]
@mateuszkrasucki I think this is good solution.

**Comment by mateuszkrasucki** [comment]
Done.
